# Generated by Django 4.1.2 on 2022-10-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
